import { Injectable } from "@angular/core";

export interface Phones {
    age: number
    href: string
    name: any
    imageTitle: string
    index: number
    text: string
    image: string[]

}

@Injectable({ providedIn: 'root' })
export class PhonesService {
    phones: Phones[] = [
        {

            age: 19,
            href: "Motorola%20XOOM%E2%84%A2%20with%20Wi-Fi",
            name: "Motorola XOOM\u2122 with Wi-Fi",
            imageTitle: "../../assets/img/motorola-xoom-with-wi-fi.0.jpg",
            image: ["../../assets/img/motorola-xoom-with-wi-fi.0.jpg",
                "../../assets/img/Motorola XOOM™ with Wi-Fi/motorola-xoom-with-wi-fi.1.jpg",
                "../../assets/img/Motorola XOOM™ with Wi-Fi/motorola-xoom-with-wi-fi.2.jpg",
                "../../assets/img/Motorola XOOM™ with Wi-Fi/motorola-xoom-with-wi-fi.3.jpg",
                "../../assets/img/Motorola XOOM™ with Wi-Fi/motorola-xoom-with-wi-fi.4.jpg",
                "../../assets/img/Motorola XOOM™ with Wi-Fi/motorola-xoom-with-wi-fi.5.jpg"
            ],

            index: 0,
            text: "Motorola XOOM with Wi-Fi has a super-powerful dual-core processor and Android™ 3.0 (Honeycomb) — the Android platform designed specifically for tablets. With its 10.1-inch HD widescreen display, you’ll enjoy HD video in a thin, light, powerful and upgradeable tablet.",
        },
        {
            age: 18,
            name: "MOTOROLA XOOM\u2122",
            href: "MOTOROLA%20XOOM%E2%84%A2",
            imageTitle: "../../assets/img/MOTOROLA XOOM™/motorola-xoom.0.jpg",
            image: ["../../assets/img/MOTOROLA XOOM™/motorola-xoom.0.jpg",
                "../../assets/img/MOTOROLA XOOM™/motorola-xoom.1.jpg",
                "../../assets/img/MOTOROLA XOOM™/motorola-xoom.2.jpg",
            ],
            index: 1,
            text: "MOTOROLA XOOM has a super-powerful dual-core processor and Android™ 3.0 (Honeycomb) — the Android platform designed specifically for tablets. With its 10.1-inch HD widescreen display, you’ll enjoy HD video in a thin, light, powerful and upgradeable tablet.",
        },
        {
            age: 17,
            name: "MOTOROLA ATRIX\u2122 4G",
            href: "MOTOROLA%20ATRIX%E2%84%A2%204G",
            imageTitle: "../../assets/img/Motorola ATRIX/motorola-atrix-4g.0.jpg",
            image: ["../../assets/img/Motorola ATRIX/motorola-atrix-4g.0.jpg",
                "../../assets/img/Motorola ATRIX/motorola-atrix-4g.1.jpg",
                "../../assets/img/Motorola ATRIX/motorola-atrix-4g.2.jpg",
                "../../assets/img/Motorola ATRIX/motorola-atrix-4g.3.jpg",],
            index: 2,
            text: "MOTOROLA ATRIX 4G gives you dual-core processing power and the revolutionary webtop application. With webtop and a compatible Motorola docking station, sold separately, you can surf the Internet with a full Firefox browser, create and edit docs, or access multimedia on a large screen almost anywhere.",
        },
        {
            age: 16,
            name: "Dell Streak 7",
            href: "Dell%20Streak%207",
            imageTitle: "../../assets/img/Dell Streak 7/dell-streak-7.0.jpg",
            image: ["../../assets/img/Dell Streak 7/dell-streak-7.0.jpg",
                "../../assets/img/Dell Streak 7/dell-streak-7.1.jpg",
                "../../assets/img/Dell Streak 7/dell-streak-7.2.jpg",
                "../../assets/img/Dell Streak 7/dell-streak-7.3.jpg",
                "../../assets/img/Dell Streak 7/dell-streak-7.4.jpg",],
            index: 3,
            text: "Introducing Dell™ Streak 7. Share photos, videos and movies together. It’s small enough to carry around, big enough to gather around. Android™ 2.2-based tablet with over-the-air upgrade capability for future OS releases. A vibrant 7-inch, multitouch display with full Adobe® Flash 10.1 pre-installed. Includes a 1.3 MP front-facing camera for face-to-face chats on popular services such as Qik or Skype. 16 GB of internal storage, plus Wi-Fi, Bluetooth and built-in GPS keeps you in touch with the world around you. Connect on your terms. Save with 2-year contract or flexibility with prepaid pay-as-you-go plans",
        },
        {
            age: 15,
            name: "Samsung Gem\u2122",
            href: "Samsung%20Gem%E2%84%A2",
            imageTitle: "../../assets/img/Samsung Gem™/samsung-gem.0.jpg",
            image: ["../../assets/img/Samsung Gem™/samsung-gem.0.jpg",
                "../../assets/img/Samsung Gem™/samsung-gem.1.jpg",
                "../../assets/img/Samsung Gem™/samsung-gem.2.jpg",],
            index: 4,
            text: "The Samsung Gem™ maps a route to a smarter mobile experience. By pairing one of the fastest processors in the category with the Android™ platform, the Gem delivers maximum multitasking speed and social networking capabilities to let you explore new territory online. A smart phone at an even smarter price is a real find, so uncover the Gem and discover what’s next.",
        },
        {
            age: 14,
            name: "Dell Venue",
            href: "Dell%20Venue",
            imageTitle: "../../assets/img/Dell Venue/dell-venue.0.jpg",
            image: ["../../assets/img/Dell Venue/dell-venue.0.jpg",
                "../../assets/img/Dell Venue/dell-venue.1.jpg",
                "../../assets/img/Dell Venue/dell-venue.2.jpg",
                "../../assets/img/Dell Venue/dell-venue.3.jpg",
                "../../assets/img/Dell Venue/dell-venue.4.jpg",
                "../../assets/img/Dell Venue/dell-venue.5.jpg",],
            index: 5,
            text: "The Venue is the perfect one-touch, Smart Phone providing instant access to everything you love. All of Venue's features make it perfect for on-the-go students, mobile professionals, and active social communicators who love style and performance. Elegantly designed, the Venue offers a vibrant, curved glass display that’s perfect for viewing all types of content. The Venue’s slender form factor feels great in your hand and also slips easily into your pocket. A mobile entertainment powerhouse that lets you download the latest tunes from Amazon MP3 or books from Kindle, watch video, or stream your favorite radio stations. All on the go, anytime, anywhere.",
        },
        {
            age: 13,
            name: "Nexus S",
            href: "Nexus%20S",
            imageTitle: "../../assets/img/Nexus S/nexus-s.0.jpg",
            image: ["../../assets/img/Nexus S/nexus-s.0.jpg",
                "../../assets/img/Nexus S/nexus-s.1.jpg",
                "../../assets/img/Nexus S/nexus-s.2.jpg",
                "../../assets/img/Nexus S/nexus-s.3.jpg",],
            index: 6,
            text: "Nexus S is the next generation of Nexus devices, co-developed by Google and Samsung. The latest Android platform (Gingerbread), paired with a 1 GHz Hummingbird processor and 16GB of memory, makes Nexus S one of the fastest phones on the market. It comes pre-installed with the best of Google apps and enabled with new and popular features like true multi-tasking, Wi-Fi hotspot, Internet Calling, NFC support, and full web browsing. With this device, users will also be the first to receive software upgrades and new Google mobile apps as soon as they become available. For more details, visit http://www.google.com/nexus.",
        },
        {
            age: 12,
            name: "LG Axis",
            href: "LG%20Axis",
            imageTitle: "../../assets/img/LG Axis/lg-axis.0.jpg",
            image: ["../../assets/img/LG Axis/lg-axis.0.jpg",
                "../../assets/img/LG Axis/lg-axis.1.jpg",
                "../../assets/img/LG Axis/lg-axis.2.jpg"],
            index: 7,
            text: "Android plus QWERTY is a powerful duo. LG Axis melds a speedy UI with the limitless micro-entertainment of 80,000+ apps including voice-activated Google. Feel the tactile vibration on its tempered glass touchscreen. Take the fuzziness out of your fun with a 3.2MP camera that does 360° panoramics. And customize your home screens with shortcuts to your apps, favorites, and widgets. It's the centerpiece of your life.",

        },
        {
            age: 11,
            name: "Samsung Galaxy Tab\u2122",
            href: "Samsung%20Galaxy%20Tab%E2%84%A2",
            imageTitle: "../../assets/img/Samsung Galaxy Tab™/samsung-galaxy-tab.0.jpg",
            image: ["../../assets/img/Samsung Galaxy Tab™/samsung-galaxy-tab.0.jpg",
                "../../assets/img/Samsung Galaxy Tab™/samsung-galaxy-tab.1.jpg",
                "../../assets/img/Samsung Galaxy Tab™/samsung-galaxy-tab.2.jpg",
                "../../assets/img/Samsung Galaxy Tab™/samsung-galaxy-tab.3.jpg",
                "../../assets/img/Samsung Galaxy Tab™/samsung-galaxy-tab.4.jpg",
                "../../assets/img/Samsung Galaxy Tab™/samsung-galaxy-tab.5.jpg",],
            index: 8,
            text: "Feel Free to Tab™. The Samsung Galaxy Tab™, the tablet device that delivers enhanced capabilities with advanced mobility, has a large, perfectly sized, 7.0 screen that offers plenty of room for the thousands of interactive games and apps available for the Android™ platform, and its slim design makes it perfect for travel and one-handed grip. Use the Galaxy Tab to relax and enjoy an e-book, watch rich video or full web content with its Adobe® Flash® Player compatibility, video chat using the front-facing camera, or send user-generated content wirelessly to other devices like your TV via AllShare™. With so many options for customization and interactivity, the Galaxy Tab gives you everything you want, anywhere you go…Feel Free to Tab™.",
        },
        {
            age: 10,
            name: "Samsung Showcase\u2122 a Galaxy S\u2122 phone",
            href: "Samsung%20Showcase%E2%84%A2%20a%20Galaxy%20S%E2%84%A2%20phone",
            imageTitle: "../../assets/img/Samsung Showcase™ a Galaxy S™ phone/samsung-showcase-a-galaxy-s-phone.0.jpg",
            image: ["../../assets/img/Samsung Showcase™ a Galaxy S™ phone/samsung-showcase-a-galaxy-s-phone.0.jpg",
                "../../assets/imgSamsung Showcase™ a Galaxy S™ phone/samsung-showcase-a-galaxy-s-phone.1.jpg",
                "../../assets/img/Samsung Showcase™ a Galaxy S™ phone/samsung-showcase-a-galaxy-s-phone.2.jpg",],
            index: 9,
            text: "Experience entertainment in a whole new light. The stylish and slim Samsung Showcase™, with its vivid 4-inch Super AMOLED™ display, makes everything from Hollywood blockbusters to music videos to Amazon’s bestsellers look absolutely brilliant – even outside in the sun. Android™ Market rockets you into a universe filled with equally brilliant apps; download them at blistering speeds thanks to the powerful 1GHz Hummingbird processor. Keep your social life organized and continuously updated with the pre-loaded social networking apps, while uploading all the 5.0MP pics you’ve snapped and 720p HD videos you’ve recorded",
        },
        {
            age: 9,
            name: "DROID\u2122 2 Global by Motorola",
            href: "DROID%E2%84%A2%202%20Global%20by%20Motorola",
            imageTitle: "../../assets/img/DROID™ 2 Global by Motorola/droid-2-global-by-motorola.0.jpg",
            image: ["../../assets/img/DROID™ 2 Global by Motorola/droid-2-global-by-motorola.0.jpg",
                "../../assets/img/DROID™ 2 Global by Motorola/droid-2-global-by-motorola.1.jpg",
                "../../assets/img/DROID™ 2 Global by Motorola/droid-2-global-by-motorola.2.jpg",],
            index: 10,
            text: "With Quad Band GSM, the DROID 2 Global can send email and make and receive calls from more than 200 countries. It features an improved QWERTY keyboard, super-fast 1.2 GHz processor and enhanced security for all your business needs.",
        },
        {
            age: 9,
            name: "DROID\u2122 Pro by Motorola",
            href: "DROID%E2%84%A2%20Pro%20by%20Motorola",
            imageTitle: "../../assets/img/DROID™ Pro by Motorola/droid-pro-by-motorola.0.jpg",
            image: ["../../assets/img/DROID™ Pro by Motorola/droid-pro-by-motorola.0.jpg",
                "../../assets/img/DROID™ Pro by Motorola/droid-pro-by-motorola.1.jpg",],
            index: 11,
            text: "Access your work directory, email or calendar with DROID Pro by Motorola., an Android-for-business smartphone with corporate-level security. It features both a QWERTY keyboard and touchscreen, a speedy 1 GHz processor and Adobe® Flash® Player 10.",
        },
        {
            age: 8,
            name: "MOTOROLA BRAVO\u2122 with MOTOBLUR\u2122",
            href: "MOTOROLA%20BRAVO%E2%84%A2%20with%20MOTOBLUR%E2%84%A2",
            imageTitle: "../../assets/img/MOTOROLA BRAVO™ with MOTOBLUR™/motorola-bravo-with-motoblur.0.jpg",
            image: ["../../assets/img/MOTOROLA BRAVO™ with MOTOBLUR™/motorola-bravo-with-motoblur.0.jpg",
                "../../assets/img/MOTOROLA BRAVO™ with MOTOBLUR™/motorola-bravo-with-motoblur.1.jpg",
                "../../assets/img/MOTOROLA BRAVO™ with MOTOBLUR™/motorola-bravo-with-motoblur.2.jpg",],
            index: 12,
            text: "MOTOROLA BRAVO™ with MOTOBLUR™ with its large 3.7-inch touchscreen and web-browsing capabilities is sure to make an impression. And it keeps your life updated and secure through MOTOBLUR.",
        },
        {
            age: 7,
            name: "Motorola DEFY\u2122  with MOTOBLUR\u2122 ",
            href: "Motorola%20DEFY%E2%84%A2%20%20with%20MOTOBLUR%E2%84%A2",
            imageTitle: "../../assets/img/Motorola DEFY™ with MOTOBLUR™/motorola-defy-with-motoblur.0.jpg",
            image: ["../../assets/img/Motorola DEFY™ with MOTOBLUR™/motorola-defy-with-motoblur.0.jpg",
                "../../assets/img/Motorola DEFY™ with MOTOBLUR™/motorola-defy-with-motoblur.1.jpg",
                "../../assets/img/Motorola DEFY™ with MOTOBLUR™/motorola-defy-with-motoblur.2.jpg",],
            index: 13,
            text: "DEFY with MOTOBLUR is ready for everything life throws your way. It's water-resistant and dustproof, with plenty of entertainment options; and, with MOTOBLUR, it automatically delivers messages and status updates right to your home screen.",
        },
        {
            age: 6,
            name: "T-Mobile myTouch 4G ",
            href: "T-Mobile%20myTouch%204G",
            imageTitle: "../../assets/img/T-Mobile myTouch 4G/t-mobile-mytouch-4g.0.jpg",
            image: ["../../assets/img/T-Mobile myTouch 4G/t-mobile-mytouch-4g.0.jpg",
                "../../assets/img/T-Mobile myTouch 4G/t-mobile-mytouch-4g.1.jpg",
                "../../assets/img/T-Mobile myTouch 4G/t-mobile-mytouch-4g.2.jpg",
                "../../assets/img/T-Mobile myTouch 4G/t-mobile-mytouch-4g.3.jpg",
                "../../assets/img/T-Mobile myTouch 4G/t-mobile-mytouch-4g.4.jpg",
                "../../assets/img/T-Mobile myTouch 4G/t-mobile-mytouch-4g.5.jpg",],
            index: 14,
            text: "The myTouch 4G lets you connect fast, communicate easily, and share—all on America’s largest 4G network. Built with families in mind, the newest T-Mobile myTouch 4G helps solve the challenges of staying physically and emotionally connected by sharing photos and video with the HD Camcorder, spontaneous face-to-face conversations through Video Chat, and the ability to reach 4G speeds on T-Mobile’s HSPA+ network.",
        },
        {
            age: 5,
            name: "Samsung Mesmerize\u2122 a Galaxy S\u2122 phone",
            href: "Samsung%20Mesmerize%E2%84%A2%20a%20Galaxy%20S%E2%84%A2%20phone",
            imageTitle: "../../assets/img/Samsung Mesmerize™ a Galaxy S™ phone/samsung-mesmerize-a-galaxy-s-phone.0.jpg",
            image: ["../../assets/img/Samsung Mesmerize™ a Galaxy S™ phone/samsung-mesmerize-a-galaxy-s-phone.0.jpg",
                "../../assets/img/Samsung Mesmerize™ a Galaxy S™ phone/samsung-mesmerize-a-galaxy-s-phone.1.jpg",
                "../../assets/img/Samsung Mesmerize™ a Galaxy S™ phone/samsung-mesmerize-a-galaxy-s-phone.2.jpg",
                "../../assets/img/Samsung Mesmerize™ a Galaxy S™ phone/samsung-mesmerize-a-galaxy-s-phone.3.jpg",],
            index: 15,
            text: "Experience entertainment in a whole new light. The stylish and slim Samsung Mesmerize™, with its vivid 4-inch Super AMOLED™ display, makes everything from Hollywood blockbusters to music videos to Amazon’s bestsellers look absolutely brilliant – even outside in the sun. Android™ Market rockets you into a universe filled with equally brilliant apps; download them at blistering speeds thanks to the powerful 1GHz Hummingbird processor. Keep your social life organized and continuously updated with the pre-loaded social networking apps, while uploading all the 5.0MP pics you’ve snapped and 720p HD videos you’ve recorded.",
        },
        {
            age: 4,
            name: "SANYO ZIO",
            href: "SANYO%20ZIO",
            imageTitle: "../../assets/img/SANYO ZIO/sanyo-zio.0.jpg",
            image: ["../../assets/img/SANYO ZIO/sanyo-zio.0.jpg",
                "../../assets/img/SANYO ZIO/sanyo-zio.1.jpg",
                "../../assets/img/SANYO ZIO/sanyo-zio.2.jpg",],
            index: 16,
            text: "Zio uses CDMA2000 1xEV-DO rev. A and Wi-Fi technologies and features a 3.5-inch WVGA touch-screen display as a backdrop for a fully customizable mobile multimedia experience. Along with the touch-screen, a trackball helps users navigate features such as the 3.2 MP camera with video record/playback, media player and full HTML Web browser. Zio supports up to 32GB through its external microSD memory slot.",
        },
        {
            age: 3,
            name: "Samsung Transform\u2122",
            href: "Samsung%20Transform%E2%84%A2",
            imageTitle: "../../assets/img/Samsung Transform™/samsung-transform.0.jpg",
            image: ["../../assets/img/Samsung Transform™/samsung-transform.0.jpg",
                "../../assets/img/Samsung Transform™/samsung-transform.1.jpg",
                "../../assets/img/Samsung Transform™/samsung-transform.2.jpg",
                "../../assets/img/Samsung Transform™/samsung-transform.3.jpg",
                "../../assets/img/Samsung Transform™/samsung-transform.4.jpg",],
            index: 17,
            text: "Change your perspective. The Samsung Transform™ is an Android powered device that delivers the truly customizable experience you want your phone to provide. Enjoy a new and easy way to personalize your device for business or for entertainment, showcasing your own favorite theme and more through the new open software platform and the ability to download individual ‘Sprint ID Service Packs’ that combine and deliver multiple content items and applications specifically for the features you want. Combine this with the 3.5” touch display, QWERTY keyboard, high-speed processor, and both a front and rear facing camera to bring your unique mobile experience to life.",
        },
        {
            age: 2,
            name: "T-Mobile G2",
            href: "T-Mobile%20G2",
            imageTitle: "../../assets/img/T-Mobile G2/t-mobile-g2.0.jpg",
            image: ["../../assets/img/T-Mobile G2/t-mobile-g2.0.jpg",
                "../../assets/img/T-Mobile G2/t-mobile-g2.1.jpg",
                "../../assets/img/T-Mobile G2/t-mobile-g2.2.jpg",],
            index: 18,
            text: "The T-Mobile G1 was the world's first Android-powered phone. Launched nearly two years ago, it created an entirely new class of mobile phones and apps. Its successor, the T-Mobile G2 with Google, will continue the revolution. The T-Mobile G2 will deliver tight integration with Google services and break new ground as the first smartphone designed to run at 4G speeds on our new HSPA+ network.",
        },
        {
            age: 1,
            name: "Motorola CHARM\u2122 with MOTOBLUR\u2122",
            href: "Motorola%20CHARM%E2%84%A2%20with%20MOTOBLUR%E2%84%A2",
            imageTitle: "../../assets/img/Motorola CHARM™ with MOTOBLUR™/motorola-charm-with-motoblur.0.jpg",
            image: ["../../assets/img/Motorola CHARM™ with MOTOBLUR™/motorola-charm-with-motoblur.0.jpg",
                "../../assets/img/Motorola CHARM™ with MOTOBLUR™/motorola-charm-with-motoblur.1.jpg",
                "../../assets/img/Motorola CHARM™ with MOTOBLUR™/motorola-charm-with-motoblur.2.jpg",],
            index: 19,
            text: "Motorola CHARM fits easily in your pocket or palm. Includes MOTOBLUR so you can sync and merge your contacts, emails, messages and posts with continuous updates and back-ups.",
        },


    ]
    getByName(name: any) {
        return this.phones.find(p => p.name === name);
    }
}