export const PHONES = [
  {
    age: 19,
    name: "Motorola XOOM\u2122 with Wi-Fi",
    image: "../assets/img/motorola-xoom-with-wi-fi.0.jpg",
    alt: "Motorola XOOM WI-FI",
    index: 0,
    text: "The Next, Next Generation Experience the future with Motorola XOOM with Wi-Fi, the world's first tablet powered by Android 3.0 (Honeycomb).",
  },
  {
    age: 18,
    name: "MOTOROLA XOOM\u2122",
    image: "../assets/img/motorola-xoom.0.jpg",
    alt: "Motorola XOOM",
    index: 1,
    text: "The Next, Next Generation Experience the future with MOTOROLA XOOM, the world's first tablet powered by Android 3.0 (Honeycomb).",
  },
  {
    age: 17,
    name: "MOTOROLA ATRIX\u2122 4G",
    image: "../assets/img/motorola-atrix-4g.0.jpg",
    alt: "MOTOROLA ATRIX",
    index: 2,
    text: "MOTOROLA ATRIX 4G the world's most powerful smartphone.",
  },
  {
    age: 16,
    name: "Dell Streak 7",
    image: "../assets/img/dell-streak-7.0.jpg",
    alt: "Dell Streak 7",
    index: 3,
    text: "Introducing Dell™ Streak 7. Share photos, videos and movies together. It’s small enough to carry around, big enough to gather around.",
  },
  {
    age: 15,
    name: "Samsung Gem\u2122",
    image: "../assets/img/samsung-gem.0.jpg",
    alt: "Samsung Gem",
    index: 4,
    text: "The Samsung Gem™ brings you everything that you would expect and more from a touch display smart phone – more apps, more features and a more affordable price.",
  },
  {
    age: 14,
    name: "Dell Venue",
    image: "../assets/img/dell-venue.0.jpg",
    alt: "Dell Venue",
    index: 5,
    text: "The Dell Venue; Your Personal Express Lane to Everything.",
  },
  {
    age: 13,
    name: "Nexus S",
    image: "../assets/img/nexus-s.0.jpg",
    alt: "Nexus S",
    index: 6,
    text: "Fast just got faster with Nexus S. A pure Google experience, Nexus S is the first phone to run Gingerbread (Android 2.3), the fastest version of Android yet.",
  },
  {
    age: 12,
    name: "LG Axis",
    image: "../assets/img/lg-axis.0.jpg",
    alt: "LG Axis",
    index: 7,
    text: "Android Powered, Google Maps Navigation, 5 Customizable Home Screens",

  },
  {
    age: 11,
    name: "Samsung Galaxy Tab\u2122",
    image: "../assets/img/samsung-galaxy-tab.0.jpg",
    alt: "Samsung Galaxy Tab",
    index: 8,
    text: "Feel Free to Tab™. The Samsung Galaxy Tab™ brings you an ultra-mobile entertainment experience through its 7” display, high-power processor and Adobe® Flash® Player compatibility.",
  },
  {
    age: 10,
    name: "Samsung Showcase\u2122 a Galaxy S\u2122 phone",
    image: "../assets/img/samsung-showcase-a-galaxy-s-phone.0.jpg",
    alt: "Samsung Showcase",
    index: 9,
    text: "The Samsung Showcase™ delivers a cinema quality experience like you’ve never seen before. Its innovative 4” touch display technology provides rich picture brilliance, even outdoors",
  },
  {
    age: 9,
    name: "DROID\u2122 2 Global by Motorola",
    image: "../assets/img/droid-2-global-by-motorola.0.jpg",
    alt: "DROID",
    index: 10,
    text: "The first smartphone with a 1.2 GHz processor and global capabilities.",
  },
  {
    age: 9,
    name: "DROID\u2122 Pro by Motorola",
    image: "../assets/img/droid-pro-by-motorola.0.jpg",
    alt: "DROID",
    index: 11,
    text: "The next generation of DOES.",
  },
  {
    age: 8,
    name: "MOTOROLA BRAVO\u2122 with MOTOBLUR\u2122",
    image: "../assets/img/motorola-bravo-with-motoblur.0.jpg",
    alt: "MOTOROLA BRAVO",
    index: 12,
    text: "An experience to cheer about.",
  },
  {
    age: 7,
    name: "Motorola DEFY\u2122  with MOTOBLUR\u2122 ",
    image: "../assets/img/motorola-defy-with-motoblur.0.jpg",
    alt: "Motorola DEFY",
    index: 13,
    text: "Are you ready for everything life throws your way?",
  },
  {
    age: 6,
    name: "T-Mobile myTouch 4G ",
    image: "../assets/img/t-mobile-mytouch-4g.0.jpg",
    alt: "T-Mobile myTouch 4G",
    index: 14,
    text: "The T-Mobile myTouch 4G is a premium smartphone designed to deliver blazing fast 4G speeds so that you can video chat from practically anywhere, with or without Wi-Fi.",
  },
  {
    age: 5,
    name: "Samsung Mesmerize\u2122 a Galaxy S\u2122 phone",
    image: "../assets/img/samsung-mesmerize-a-galaxy-s-phone.0.jpg",
    alt: "TSamsung Mesmerize",
    index: 15,
    text: "The Samsung Mesmerize™ delivers a cinema quality experience like you’ve never seen before. Its innovative 4” touch display technology provides rich picture brilliance,even outdoors",
  },
  {
    age: 4,
    name: "SANYO ZIO",
    image: "../assets/img/sanyo-zio.0.jpg",
    alt: "SANYO ZIO",
    index: 16,
    text: "The Sanyo Zio by Kyocera is an Android smartphone with a combination of ultra-sleek styling, strong performance and unprecedented value.",
  },
  {
    age: 3,
    name: "Samsung Transform\u2122",
    image: "../assets/img/samsung-transform.0.jpg",
    alt: "Samsung Transform",
    index: 17,
    text: "The Samsung Transform™ brings you a fun way to customize your Android powered touch screen phone to just the way you like it through your favorite themed “Sprint ID Service Pack”.",
  },
  {
    age: 2,
    name: "T-Mobile G2",
    image: "../assets/img/t-mobile-g2.0.jpg",
    alt: "T-Mobile G2",
    index: 18,
    text: "The T-Mobile G2 with Google is the first smartphone built for 4G speeds on T-Mobile's new network. Get the information you need, faster than you ever thought possible.",
  },
  {
    age: 1,
    name: "Motorola CHARM\u2122 with MOTOBLUR\u2122",
    image: "../assets/img/motorola-charm-with-motoblur.0.jpg",
    alt: "Motorola CHARM",
    index: 19,
    text: "Motorola CHARM fits easily in your pocket or palm. Includes MOTOBLUR service.",
  },
];



